# Generated by Django 3.2.2 on 2021-06-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level_of_advancement',
            field=models.PositiveSmallIntegerField(choices=[(1, 'beginner'), (2, 'medium'), (3, 'advanced')], default=1),
        ),
    ]
